on: push
name: Cloudflare Pages
permissions:
  contents: read
  deployments: write
jobs:
  cloudflare-pages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: true
      - uses: actions/setup-python@v5.0.0
        with:
          cache: pip
      - uses: actions/setup-node@v4.0.0
        with:
          cache: npm
      - run: |
          pip install -r requirements.txt
          pygbag --ume_block 0 --icon game/favicon.png --title "Star Guard" --can_close 1 --build game/pygbag
          npm ci
          npm run build
      - uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 9839aabb4253ed85d80549a8f99ee832
          projectName: fiblog
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
